import { useMemo, useState } from 'react';
import { BadgeCheck, BookOpenCheck, Building2, CheckCircle2, ExternalLink, Search, ShieldCheck, XCircle } from 'lucide-react';
import { useListDirectoryEntries, useVerifyDirectoryNumber, type DirectoryEntry } from '@workspace/api-client-react';
import { EmptyState, ErrorState, LoadingButton, PageHeading, ProtectedNote, RiskBadge, Skeleton } from '@/components/ui-pieces';

function DirectoryCard({ entry, onVerify }: { entry: DirectoryEntry; onVerify: (entry: DirectoryEntry) => void }) {
  return <article className="rounded-2xl border border-card-border bg-card p-5 shadow-[var(--shadow-sm)] transition-all hover:-translate-y-0.5 hover:shadow-[var(--shadow-md)]" data-testid={`card-directory-entry-${entry.id}`}><div className="flex items-start justify-between gap-3"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-secondary text-secondary-foreground"><Building2 size={18} /></div><div><p className="text-[13px] font-extrabold">{entry.institution}</p><p className="mt-1 text-[10px] text-muted-foreground">{entry.category} · {entry.purpose}</p></div></div><RiskBadge level={entry.priority} /></div><div className="mt-5 rounded-xl bg-muted/60 p-3"><p className="font-mono text-[15px] font-medium tracking-[-.03em]">{entry.number}</p><p className="mt-1 text-[10px] text-muted-foreground">Last verified {entry.lastVerified}</p></div><div className="mt-4 flex items-center justify-between"><span className="inline-flex items-center gap-1.5 text-[10px] text-muted-foreground"><BadgeCheck size={14} className="text-primary" /> Source: {entry.source}</span><button onClick={() => onVerify(entry)} className="inline-flex items-center gap-1.5 text-[11px] font-bold text-primary hover:underline" data-testid={`button-verify-entry-${entry.id}`}>Verify again <ExternalLink size={12} /></button></div></article>;
}

export default function Directory() {
  const directoryQuery = useListDirectoryEntries();
  const verifyNumber = useVerifyDirectoryNumber();
  const [search, setSearch] = useState('');
  const [institution, setInstitution] = useState('');
  const [number, setNumber] = useState('');
  const entries = directoryQuery.data ?? [];
  const filtered = useMemo(() => entries.filter(entry => `${entry.institution} ${entry.number} ${entry.category} ${entry.purpose}`.toLowerCase().includes(search.toLowerCase())), [entries, search]);
  const verify = (entry?: DirectoryEntry) => {
    const targetInstitution = entry?.institution ?? institution;
    const targetNumber = entry?.number ?? number;
    if (!targetInstitution) return;
    setInstitution(targetInstitution); setNumber(targetNumber);
    verifyNumber.mutate({ data: { institution: targetInstitution, number: targetNumber } });
  };
  return <div>
    <PageHeading eyebrow="Verification directory / 03" title="Verify from the source." description="A short, independent directory of official numbers. If a caller asks you to call back, start here." />
    <div className="grid gap-6 xl:grid-cols-[.74fr_1.26fr]">
      <section className="h-fit rounded-2xl border border-card-border bg-card p-5 shadow-[var(--shadow-sm)] md:p-6"><div className="mb-5 flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><ShieldCheck size={19} /></div><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-primary">Independent check</p><h2 className="mt-1 text-[17px] font-extrabold tracking-[-.035em]">Check a claimed number</h2></div></div><p className="mb-5 text-[12px] leading-relaxed text-muted-foreground">Search the official number yourself instead of calling back from a message, caller ID, or voice prompt.</p><div className="space-y-4"><label className="block"><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-[.1em] text-muted-foreground">Institution</span><input value={institution} onChange={e => setInstitution(e.target.value)} placeholder="Bank, courier, government office..." className="h-10 w-full rounded-xl border border-input bg-background px-3 text-[12px] outline-none focus:ring-2 focus:ring-ring/30" data-testid="input-directory-institution" /></label><label className="block"><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-[.1em] text-muted-foreground">Number (optional)</span><input value={number} onChange={e => setNumber(e.target.value)} placeholder="+91 80 4000 1234" className="h-10 w-full rounded-xl border border-input bg-background px-3 text-[12px] outline-none focus:ring-2 focus:ring-ring/30" data-testid="input-directory-number" /></label><LoadingButton loading={verifyNumber.isPending} onClick={() => verify()} disabled={!institution.trim()} className="w-full" data-testid="button-verify-number"><BookOpenCheck size={15} /> Verify independently</LoadingButton></div>{verifyNumber.data && <div className={`mt-5 rounded-xl border p-4 ${verifyNumber.data.verified ? 'border-primary/25 bg-primary/5' : 'border-destructive/25 bg-destructive/5'}`} data-testid="status-verification-result"><div className="flex items-start gap-2.5">{verifyNumber.data.verified ? <CheckCircle2 className="shrink-0 text-primary" size={17} /> : <XCircle className="shrink-0 text-destructive" size={17} />}<div><p className="text-[12px] font-bold">{verifyNumber.data.verified ? 'Number found in the directory' : 'No verified match found'}</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">{verifyNumber.data.message}</p>{verifyNumber.data.officialNumber && <p className="mt-2 font-mono text-[12px] font-medium">{verifyNumber.data.officialNumber}</p>}</div></div></div>}<ProtectedNote>Verification compares against an independent source. It does not prove who is speaking to you.</ProtectedNote></section>
      <section><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-[13px] font-extrabold">Official numbers</p><p className="mt-1 text-[11px] text-muted-foreground">{entries.length} sources curated for safer callbacks</p></div><label className="relative block sm:w-[220px]"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search directory" className="h-9 w-full rounded-xl border border-input bg-card pl-9 pr-3 text-[11px] outline-none focus:ring-2 focus:ring-ring/30" data-testid="input-directory-search" /></label></div>{directoryQuery.isLoading ? <div className="grid gap-4 md:grid-cols-2">{[1, 2, 3, 4].map(i => <Skeleton key={i} className="h-[210px]" />)}</div> : directoryQuery.isError ? <ErrorState message="The verification directory is unavailable." /> : filtered.length === 0 ? <EmptyState title="No matching numbers" body="Try a broader institution name, category, or purpose." icon={Search} /> : <div className="grid gap-4 md:grid-cols-2">{filtered.map(entry => <DirectoryCard key={entry.id} entry={entry} onVerify={verify} />)}</div>}</section>
    </div>
  </div>;
}