import { useState, type FormEvent } from 'react';
import { Check, Phone, Plus, ShieldCheck, UserRound, UsersRound } from 'lucide-react';
import { useCreateTrustedPerson, useListTrustedPeople, type TrustedPerson } from '@workspace/api-client-react';
import { EmptyState, ErrorState, LoadingButton, PageHeading, ProtectedNote, Skeleton } from '@/components/ui-pieces';

const initials = (name: string) => name.split(' ').map(part => part[0]).slice(0, 2).join('').toUpperCase();

function PersonCard({ person }: { person: TrustedPerson }) {
  return <article className="group rounded-2xl border border-card-border bg-card p-4 shadow-[var(--shadow-sm)] transition-all hover:-translate-y-0.5 hover:shadow-[var(--shadow-md)]" data-testid={`card-trusted-person-${person.id}`}><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-secondary font-mono text-[12px] font-medium text-secondary-foreground">{initials(person.name)}</div><div><h3 className="text-[13px] font-extrabold">{person.name}</h3><p className="mt-0.5 text-[11px] text-muted-foreground">{person.relationship}</p></div></div>{person.verified ? <span className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2 py-1 font-mono text-[9px] uppercase tracking-[.08em] text-primary"><Check size={11} /> Verified</span> : <span className="rounded-full bg-muted px-2 py-1 font-mono text-[9px] uppercase tracking-[.08em] text-muted-foreground">Pending</span>}</div><div className="mt-5 flex items-center justify-between border-t border-border/70 pt-3"><div><p className="font-mono text-[12px] font-medium">{person.phone}</p><p className="mt-1 text-[10px] capitalize text-muted-foreground">{person.channel} channel</p></div><Phone size={16} className="text-primary/60" /></div></article>;
}

export default function Trusted() {
  const peopleQuery = useListTrustedPeople();
  const createPerson = useCreateTrustedPerson();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ name: '', relationship: '', phone: '', channel: 'phone' });
  const people = peopleQuery.data ?? [];
  const update = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const submit = (event: FormEvent) => {
    event.preventDefault();
    createPerson.mutate({ data: form }, { onSuccess: () => { setForm({ name: '', relationship: '', phone: '', channel: 'phone' }); setOpen(false); peopleQuery.refetch(); } });
  };
  return <div>
    <PageHeading eyebrow="People / 02" title="Your trusted circle." description="People you can call back when a voice interaction feels uncertain. Keep this small, current, and familiar." action={<button onClick={() => setOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-[12px] font-bold text-primary-foreground transition-transform hover:-translate-y-0.5" data-testid="button-add-trusted-person"><Plus size={16} /> Add trusted person</button>} />
    <ProtectedNote>Only names and contact details are used here. BhashaShield does not read your contacts or send messages on your behalf.</ProtectedNote>
    {open && <div className="mt-5 rounded-2xl border border-primary/20 bg-primary/[.035] p-5 md:p-6"><div className="mb-5 flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-primary">New contact</p><h2 className="mt-1 text-[17px] font-extrabold">Add someone you trust</h2></div><button onClick={() => setOpen(false)} className="text-[11px] font-bold text-muted-foreground hover:text-foreground" data-testid="button-cancel-trusted-person">Cancel</button></div><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-[.1em] text-muted-foreground">Full name</span><input required value={form.name} onChange={e => update('name', e.target.value)} placeholder="e.g. Meera Iyer" className="h-10 w-full rounded-xl border border-input bg-background px-3 text-[12px] outline-none focus:ring-2 focus:ring-ring/30" data-testid="input-trusted-name" /></label><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-[.1em] text-muted-foreground">Relationship</span><input required value={form.relationship} onChange={e => update('relationship', e.target.value)} placeholder="e.g. Daughter" className="h-10 w-full rounded-xl border border-input bg-background px-3 text-[12px] outline-none focus:ring-2 focus:ring-ring/30" data-testid="input-trusted-relationship" /></label><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-[.1em] text-muted-foreground">Phone number</span><input required type="tel" value={form.phone} onChange={e => update('phone', e.target.value)} placeholder="+91 98 7654 3210" className="h-10 w-full rounded-xl border border-input bg-background px-3 text-[12px] outline-none focus:ring-2 focus:ring-ring/30" data-testid="input-trusted-phone" /></label><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-[.1em] text-muted-foreground">Preferred channel</span><select value={form.channel} onChange={e => update('channel', e.target.value)} className="h-10 w-full rounded-xl border border-input bg-background px-3 text-[12px] font-semibold outline-none focus:ring-2 focus:ring-ring/30" data-testid="select-trusted-channel"><option value="phone">Phone call</option><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option></select></label><div className="md:col-span-2"><LoadingButton type="submit" loading={createPerson.isPending} data-testid="button-save-trusted-person"><ShieldCheck size={15} /> Save trusted person</LoadingButton></div></form></div>}
    <div className="mt-8 flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-secondary text-secondary-foreground"><UsersRound size={17} /></div><div><p className="text-[13px] font-extrabold">A second voice can change the decision</p><p className="text-[11px] text-muted-foreground">Your trusted circle is always one tap away from a review.</p></div></div>
    {peopleQuery.isLoading ? <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[1, 2, 3].map(i => <Skeleton key={i} className="h-[145px]" />)}</div> : peopleQuery.isError ? <div className="mt-5"><ErrorState message="Trusted people could not be loaded." /></div> : people.length === 0 ? <div className="mt-5"><EmptyState title="Your trusted circle is empty" body="Add one person you would call when a caller asks for money, codes, or an urgent decision." icon={UserRound} /></div> : <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{people.map(person => <PersonCard key={person.id} person={person} />)}</div>}
    <div className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-border bg-card/60 p-4"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-primary">Good practice</p><p className="mt-2 text-[12px] font-bold">Use a number you already know.</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">Never add a contact because a caller tells you to.</p></div><div className="rounded-2xl border border-border bg-card/60 p-4"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-primary">Keep current</p><p className="mt-2 text-[12px] font-bold">Review this list every few months.</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">Old numbers can create a false sense of safety.</p></div><div className="rounded-2xl border border-border bg-card/60 p-4"><p className="font-mono text-[10px] uppercase tracking-[.13em] text-primary">Your control</p><p className="mt-2 text-[12px] font-bold">BhashaShield only suggests.</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">You choose who to contact and what to share.</p></div></div>
  </div>;
}